service: github-slack-pr-bot

provider:
  name: aws
  runtime: nodejs8.10
  timeout: 30
  deploymentBucket:
    name: sc-lambda-${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action: "xray:*"
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 1
  dotenv:
    path: ./.env

package:
  - exclude:
    - ./**
  - include:
    - ./node_modules/**
    - ./dist/**

functions:
  GitHubSlackCommManager:
    handler: dist/src/handlers/GitHubManager.handler
    events:
      - http:
          path: github
          method: post
  SlackTeamStatusManager:
    handler: dist/src/handlers/SlackTeamStatus.handler
    events:
      - http:
          path: team-status
          method: post

resources:
  Resources:
    GitHubSlackCommManagerLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        TracingConfig:
          Mode: Active
    SlackTeamStatusManagerLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        TracingConfig:
          Mode: Active
